name: Generate Contribution Snake

on:
  # Automatically runs every 24 hours
  schedule:
    - cron: "0 0 * * *"

  # Allows manual trigger from GitHub UI
  workflow_dispatch:

  # Also runs when code is pushed to master
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate contribution snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=#cba6f7&color_dots=#313244,#6c7086,#9399b2,#b4befe,#cba6f7&color_progress=#cba6f7

      - name: Upload snake SVG to snake branch
        uses: crazy-max/ghaction-github-pages@v4.2.0
        with:
          target_branch: snake
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}